apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: generic-builder
  namespace: kpack-builders
spec:
  tag: driv/generic-builder
  order:
  - group:
    - id: paketo-buildpacks/go
  - group:
    - id: paketo-buildpacks/java
  # - group:
  #   - id: paketo-buildpacks/dotnet-core
  # - group:
  #   - id: paketo-buildpacks/nodejs
  serviceAccountName: kpack-service-account
  stack:
    kind: ClusterStack
    name: base
  store:
    kind: ClusterStore
    name: default
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  # - image: gcr.io/paketo-buildpacks/dotnet-core
  - image: gcr.io/paketo-buildpacks/go
  - image: gcr.io/paketo-buildpacks/java
  # - image: gcr.io/paketo-buildpacks/nodejs
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: "paketobuildpacks/build-jammy-base:0.1.115" # {"$imagepolicy": "flux-system:build-jammy-base"}
  runImage:
    image: "paketobuildpacks/run-jammy-base:0.1.113" # {"$imagepolicy": "flux-system:run-jammy-base"}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: "build-jammy-base"
  namespace: flux-system
spec:
  image: "paketobuildpacks/build-jammy-base"
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: "run-jammy-base"
  namespace: flux-system
spec:
  image: "paketobuildpacks/run-jammy-base"
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: "build-jammy-base"
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: "build-jammy-base"
  policy:
    semver:
      range: '>0.1.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: "run-jammy-base"
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: "run-jammy-base"
  policy:
    semver:
      range: '>0.1.0'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: kpack-builders
secrets:
- name: registry-credentials
- name: git-credentials
imagePullSecrets:
- name: registry-credentials
